name: AdvancementAnnouncer
version: '${project.version}'
main: io.github.altkat.advancementannouncer.AdvancementAnnouncer
api-version: 1.16
authors: [StreetMelodeez(AltKat)]
softdepend: ["PlaceholderAPI", "UltimateAdvancementAPI"]
commands:
  advancementannouncer:
    usage: /advancementannouncer send <style> <icon> <target> <message>
    aliases:
      - aa
permissions:
  advancementannouncer.admin:
    description: Allows full control of Advancement Announcer
    default: op
  advancementannouncer.toggle:
    description: Allows toggling announcements
    default: true